import { NativeModules } from 'react-native';
import { createLogger } from '@partneros/core';
import type { AudioFrame } from '../AudioCapture';
import type { DetectionResult, KeywordDetector } from './KeywordDetector';

const logger = createLogger({ prefix: 'OpenWakeWordDetector' });

export interface OpenWakeWordConfig {
  modelPath: string; // bundled .tflite asset path, e.g. 'models/hey_bro.tflite'
  threshold: number; // detection confidence cutoff, 0-1
}

export const DEFAULT_OWW_CONFIG: OpenWakeWordConfig = {
  modelPath: 'hey_bro.tflite',
  threshold: 0.5,
};

/**
 * Preferred KeywordDetector. Wraps a native TFLite interpreter
 * (android/.../OpenWakeWordModule.kt) running a custom "hey bro" model.
 *
 * IMPORTANT: the .tflite model itself is NOT generated by this code --
 * OpenWakeWord custom models are trained offline (their training pipeline
 * takes synthetic TTS samples of "hey bro" + augmentation, produces a
 * small ONNX->TFLite model). That trained file must be dropped into
 * android/app/src/main/assets/hey_bro.tflite before this detector can
 * actually detect anything. Until then, initialize() will throw.
 */
export class OpenWakeWordDetector implements KeywordDetector {
  readonly engineName = 'openwakeword';
  private buffer: number[] = [];
  private readonly windowSize = 16000; // 1s of audio at 16kHz, typical OWW input window
  private initialized = false;

  constructor(private config: OpenWakeWordConfig = DEFAULT_OWW_CONFIG) {}

  async initialize(): Promise<void> {
    if (!NativeModules.OpenWakeWord) {
      throw new Error('OpenWakeWord native module not linked -- see android/.../OpenWakeWordModule.kt');
    }
    await NativeModules.OpenWakeWord.loadModel(this.config.modelPath);
    this.initialized = true;
    logger.info('OpenWakeWord model loaded', { modelPath: this.config.modelPath });
  }

  async processFrame(frame: AudioFrame): Promise<DetectionResult> {
    if (!this.initialized) {
      return { detected: false, confidence: 0 };
    }

    for (let i = 0; i < frame.length; i++) this.buffer.push(frame[i]);
    if (this.buffer.length < this.windowSize) {
      return { detected: false, confidence: 0 };
    }

    // Keep a rolling window -- OWW models expect fixed-size input, slide
    // forward rather than clearing, so we don't miss the wake word
    // spanning a window boundary.
    const window = this.buffer.slice(this.buffer.length - this.windowSize);
    this.buffer = window.slice(Math.floor(this.windowSize / 2)); // 50% overlap

    const confidence: number = await NativeModules.OpenWakeWord.predict(window);
    return { detected: confidence >= this.config.threshold, confidence };
  }

  reset(): void {
    this.buffer = [];
  }

  async dispose(): Promise<void> {
    await NativeModules.OpenWakeWord?.unloadModel();
    this.initialized = false;
  }
}
